name:                whiless-hs
version:             0.1.0.0
github:              "rrajasek95/whiless-hs"
license:             BSD3
author:              "Rishi Rajasekaran"
maintainer:          "rajasekaran.rishi@gmail.com"
copyright:           "2020 Rishi Rajasekaran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rrajasek95/whiless-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck
- hspec

library:
  source-dirs: src

executables:
  whiless-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whiless-hs

tests:
  whiless-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whiless-hs
