[package]
name = "arith-rs"
version = "0.1.0"
authors = ["Rishi Rajasekaran <rajasekaran.rishi@gmail.com>"]
edition = "2018"
type_length_limit="1137931"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
