
all:
#	cd whiless-hs &&  stack install --local-bin-path ../ && mv ../whiless-hs-exe ../while-ss
	echo 'python whiless-python/while_small_step.py' > while-ss ; chmod +x while-ss

clean: while-ss
	rm while-ss
